### ISSUE TITLE
[FE] Add a decimal point display property to the numeric pad widget

### ISSUE THREAD

**Issue by drumcap** [vanillabrain/vanillameta#419]
## Description
A property is needed to display decimal points on the number pad widget.
Currently, only one fixed digit is displayed.

## Todo
- [ ] Create a display property
- [ ] Implement the property processing module
- [ ] Test the feature
