### ISSUE TITLE
database 연결 정보 수정 ( connectionConfig)

### ISSUE THREAD

**Issue by yathoo88** [vanillabrain/vanillameta#99]
## Description
front에서 사용될  database config 정보로 넘겨주고 , 조회할 수 있도록 처리

## Todo
- [x] TestConnection(연결테스트) 서비스 param, response 수정
- [x] 데이터베이스 아이템 조회 response 수정
- [x] 데이터베이스 아이템 갱신 생성
